---
- hosts: redhat
  become: yes
  remote_user: ansible

  tasks:

  - name: Install podman
    yum:
      name: podman
      state: present
     
  - name: Start and enable podman service
    service:
      name: podman
      enabled: true
      state: started    

  - name: Pull tomcat image
    containers.podman.podman_image:
      name: quay.io/diegor2324/obligatorio/tomcat

  - name: Run container
    containers.podman.podman_container:
      name: tomcatapp
      image: quay.io/diegor2324/obligatorio/tomcat
      state: started
      exposed_ports:
        - 8080      
      ports:
        - "8080:8080"

- hosts: redhat
  become: yes
  remote_user: ansible

  tasks:

  - name: Install apache
    yum:
      name: httpd
      state: present

  - name: Create virtualhost configuration directory
    file:
      path: /etc/httpd/vhosts.d
      state: directory
      owner: root

  - name: Copy virtualhost configuration
    copy:
      src: ./archivos/virtualhost.conf
      dest: /etc/httpd/vhosts.d/ejemplo.conf
    notify: Restart apache

  - name: Include vhosts directory
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional /etc/httpd/vhosts.d/*.conf

  - name: Open firewall ports
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - http
    - https

  - name: Start and enable httpd service
    service:
      name: httpd
      enabled: true
      state: started


  handlers:

      - name: Restart apache
        service:
          name: httpd
          state: restarted  
